package gametumbuhan;

import java.util.ArrayList;

public class FaktaWindow extends javax.swing.JFrame {

    public FaktaWindow() {        
        ArrayList<Fakta> listFakta = new ArrayList<Fakta>(); // Membuat list untuk menyimpan fakta
        
        // Menambahkan fakta ke list
        listFakta.add(new Fakta(1, "Dikotil merupakan batang tumbuhan yang menjadi tempat " +
                                "pertumbuhan sekunder."));
        listFakta.add(new Fakta(2, "Membuat batang tumbuhan dikotil tumbuh membesar adalah tugas " +
                              "dari jaringan kambium."));
        listFakta.add(new Fakta(3, "Kambium bertugas untuk membentuk sel-sel xilem dan floem pada " +
                                "batang dikotil."));
        listFakta.add(new Fakta(4, "Tumbuhan pisang memiliki jenis batang basah. "));
        listFakta.add(new Fakta(5, "Kaktus dan tebu memiliki kemampuan untuk menyimpan cadangan " +
                                "makanan berupa air pada batang."));
        listFakta.add(new Fakta(6, "Rambut akar dapat memperluas bidang penyerapan air dan garam " +
                                "mineral."));
        listFakta.add(new Fakta(7, "Jenis akar gantung mengisap udara untuk bernafas dan tumbuh di " +
                                "pohon beringin."));
        listFakta.add(new Fakta(8, "Jenis akar tunggang memiliki akar yang besar, panjang, dan kuat " +
                                "sebagai pusat untuk menambus jauh ke permukaan tanah."));
        listFakta.add(new Fakta(9, "Jenis akar pada padi merupakan akar serabut."));
        listFakta.add(new Fakta(10, "Jenis akar nafas dimiliki tanaman bakau yang biasanya naik keatas air " +
                                "untuk membantu pernapasan."));
        listFakta.add(new Fakta(11, "Klorofil bertugas untuk membuat makanan untuk tumbuhan dan " +
                                "menyerap cahaya."));
        listFakta.add(new Fakta(12, "Jenis daun sejajar mempunyai satu tulang di tengah yang besar dan " +
                                "lurus, biasanya aku tumbuh di pohon tebu atau padi."));
        listFakta.add(new Fakta(13, "Salah satu dari ciri-ciri daun menyirip adalah memiliki tulang " +
                                "berbentuk seperti ikan."));
        listFakta.add(new Fakta(14, "Daun sirih memiliki ciri daun yang melengkung."));
        listFakta.add(new Fakta(15, "Pohon jarak memiliki ciri daun yang menjari."));
        
        
        // Mengatur tampilan fakta agar rapi.
        String fact_to_show = "";
        for (int i = 0; i < listFakta.size(); i++) { 
            fact_to_show = fact_to_show + String.valueOf(listFakta.get(i).no_fakta) + " ." + "  " + 
                            listFakta.get(i).poin_fakta + "\n\n";
        }
     
        initComponents();
        this.setLocationRelativeTo(null);
        factArea.setEditable(false);
        factArea.setText(fact_to_show);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        factArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 255, 204));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setText("Fun Fact Tentang Tumbuhan");

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 102));

        factArea.setBackground(new java.awt.Color(242, 242, 242));
        factArea.setColumns(20);
        factArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        factArea.setRows(5);
        jScrollPane1.setViewportView(factArea);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea factArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
